apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: csv-service-ci
  namespace: csv-service-ci
spec:
  tasks:
    - name: git-clone
      params:
        - name: url
          value: 'https://github.com/suulperi/csv-service.git'
        - name: revision
          value: master
        - name: refspec
          value: ''
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: crtFileName
          value: ca-bundle.crt
        - name: subdirectory
          value: ''
        - name: sparseCheckoutDirectories
          value: ''
        - name: deleteExisting
          value: 'true'
        - name: httpProxy
          value: ''
        - name: httpsProxy
          value: ''
        - name: noProxy
          value: ''
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:e29585c67da42f3800f250c9c60159453af6ee7b4fff5669e27e17f34136a1d3
        - name: userHome
          value: /home/git
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: csv-service-sourcecode
    - name: maven
      params:
        - name: MAVEN_IMAGE
          value: >-
            image-registry.openshift-image-registry.svc:5000/openshift/ubi8-openjdk-8:1.12
        - name: GOALS
          value:
            - package
        - name: MAVEN_MIRROR_URL
          value: ''
        - name: SERVER_USER
          value: ''
        - name: SERVER_PASSWORD
          value: ''
        - name: PROXY_USER
          value: ''
        - name: PROXY_PASSWORD
          value: ''
        - name: PROXY_PORT
          value: ''
        - name: PROXY_HOST
          value: ''
        - name: PROXY_NON_PROXY_HOSTS
          value: ''
        - name: PROXY_PROTOCOL
          value: http
        - name: CONTEXT_DIR
          value: .
      runAfter:
        - git-clone
      taskRef:
        kind: ClusterTask
        name: maven
      workspaces:
        - name: source
          workspace: csv-service-sourcecode
        - name: maven-settings
          workspace: csv-service-sourcecode
    - name: buildah
      params:
        - name: IMAGE
          value: quay.io/tsohlber/csv-service
        - name: BUILDER_IMAGE
          value: >-
            registry.redhat.io/rhel8/buildah@sha256:ac0b8714cc260c94435cab46fe41b3de0ccbc3d93e38c395fa9d52ac49e521fe
        - name: STORAGE_DRIVER
          value: vfs
        - name: DOCKERFILE
          value: ./Dockerfile
        - name: CONTEXT
          value: .
        - name: TLSVERIFY
          value: 'true'
        - name: FORMAT
          value: oci
        - name: BUILD_EXTRA_ARGS
          value: ''
        - name: PUSH_EXTRA_ARGS
          value: ''
        - name: SKIP_PUSH
          value: 'false'
      runAfter:
        - maven
      taskRef:
        kind: ClusterTask
        name: buildah
      workspaces:
        - name: source
          workspace: csv-service-sourcecode
    - name: rhacs-image-scan
      params:
        - name: rox_central_endpoint
          value: rhacs-central-endpoint
        - name: rox_api_token
          value: rhacs-api-token
        - name: rox_image
          value: 'quay.io/stackrox-io/roxctl:3.71.0'
        - name: image
          value: 'quay.io/tsohlber/csv-service:latest'
        - name: output_format
          value: json
        - name: insecure-skip-tls-verify
          value: 'true'
      runAfter:
        - buildah
      taskRef:
        kind: Task
        name: rhacs-image-scan
    - name: rhacs-image-check
      params:
        - name: rox_central_endpoint
          value: rhacs-central-endpoint
        - name: rox_api_token
          value: rhacs-api-token
        - name: rox_image
          value: 'quay.io/stackrox-io/roxctl:3.71.0'
        - name: image
          value: 'quay.io/tsohlber/csv-service:latest'
        - name: output_format
          value: table
        - name: insecure-skip-tls-verify
          value: 'true'
      runAfter:
        - buildah
      taskRef:
        kind: Task
        name: rhacs-image-check
    - name: rhacs-deployment-check
      params:
        - name: rox_central_endpoint
          value: rhacs-central-endpoint
        - name: rox_api_token
          value: rhacs-api-token
        - name: rox_image
          value: 'quay.io/stackrox-io/roxctl:3.71.0'
        - name: deployment
          value: /workspace/source/openshift/csv-deployment.yaml
        - name: output_format
          value: table
        - name: insecure-skip-tls-verify
          value: 'true'
      runAfter:
        - buildah
      taskRef:
        kind: Task
        name: rhacs-deployment-check
      workspaces:
        - name: source
          workspace: csv-service-sourcecode
  workspaces:
    - name: csv-service-sourcecode
      optional: false

