apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: csv-service-subscription-1
  namespace: csv-service
  annotations:
    apps.open-cluster-management.io/git-branch: master
    apps.open-cluster-management.io/git-path: openshift
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: csv-service
spec:
  channel: ggithubcom-suulperi-csv-service-ns/ggithubcom-suulperi-csv-service
  placement:
    placementRef:
      name: csv-service-placement-1
      kind: PlacementRule